Fix react-redux Typescript 3.x incompatibility
The new keyof behavior in Typescript is a breaking change which affects react-redux,
producing this error:

/Users/aneil/code/precisely/web/app-client/node_modules/@types/react-redux/index.d.ts
(26,48): error TS2344: Type 'keyof T' does not satisfy the constraint 'string'.
  Type 'string | number | symbol' is not assignable to type 'string'.
    Type 'number' is not assignable to type 'string'.

The change to tsconfig.json reverts the behavior.

I also include an upgrade of react-redux to latest.